#number lines
add-highlighter global/ number-lines -relative
# show matching symbols
add-highlighter global/ show-matching
#tab scroll
hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
}
#plugin manager
evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload
#bar
plug "andreyorst/powerline.kak" defer powerline_palenight %{
    powerline-theme palenight
} config %{
    #powerline-start
}
#auto pair
plug "alexherbo2/auto-pairs.kak" config %{
       enable-auto-pairs
}
#tabs
plug "andreyorst/smarttab.kak"defer smarttab %{
    set-option global softtabstop 4
}
#clipboard
plug "lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
}
#lsp enable
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
    lsp-inlay-diagnostics 
}
#colorscheme
colorscheme palenight

